theme: minima
title: Erick Anangwe Portfolio Page
author: Anangwe
description: This is a page where you will find details about ML Engineer Erick Anangwe. This includes his education, experience, projects, events and fun activities
